# Ruuvi Network Serverless v0.01
#
# For full config options: docs.serverless.com

service: ruuvi-network-serverless

custom:
  dynamoTableName: 'RuuviSensorData'
  writerQueueName: 'ruuvi_network'
  lambdaConcurrency: 10
  dynamoWriteCapacity: 1
  dynamoReadCapacity: 1

provider:
  name: aws
  runtime: nodejs12.x
  profile: ruuvi

  # Defaults
  stage: dev
  region: eu-west-1

  # Permissions (Note: These could be more granular per lambda)
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
      Resource: { 'Fn::Join': [':', ['arn:aws:logs', { Ref: 'AWS::Region' }, { Ref: 'AWS::AccountId' }, '*']] }
    - Effect: "Allow"
      Action:
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: { 'Fn::Join': [':', ['arn:aws:logs', { Ref: 'AWS::Region' }, { Ref: 'AWS::AccountId' }, 'log-group:/aws/lambda/*writeToDatabase:*']]}
    - Effect: "Allow"
      Action:
        - "sqs:DeleteMessage"
        - "sqs:ReceiveMessage"
        - "sqs:SendMessage"
        - "sqs:GetQueueAttributes"
      Resource: "arn:aws:sqs:*"
    - Effect: "Allow"
      Action:
        - "dynamodb:DeleteItem"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:Scan"
        - "dynamodb:UpdateItem"
        - "dynamodb:BatchWriteItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:Query"
      Resource: { 'Fn::Join': [':', ['arn:aws:dynamodb', { Ref: 'AWS::Region' }, { Ref: 'AWS::AccountId' }, 'table/*']] }

# Lambdas
functions:
  requestToSQS:
    handler: requestToSQS/index.handler
    reservedConcurrency: ${self:custom.lambdaConcurrency}
    events:
      - http: POST record
    environment:
      TARGET_QUEUE: { Ref: GatewayQueue }

  writeToDatabase:
    handler: writeToDatabase/index.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - GatewayQueue
              - Arn
          batchSize: 10
    environment:
      TABLE_NAME: ${self:custom.dynamoTableName}

  getSensorData:
    handler: getSensorData/index.handler
    events:
      - http: GET get
    environment:
      TABLE_NAME: ${self:custom.dynamoTableName}
      ACCESS_KEY: "" # Empty for not required

# Resources (queues, databases, etc.)
resources:
    Resources:
      GatewayQueue:
        Type: AWS::SQS::Queue
        Properties:
          QueueName: ${self:custom.writerQueueName}
      DynamoSensorData:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: ${self:custom.dynamoTableName}
          AttributeDefinitions:
            - AttributeName: SensorId
              AttributeType: S
            - AttributeName: MeasurementTimestamp
              AttributeType: N
          KeySchema:
            - AttributeName: SensorId
              KeyType: HASH
            - AttributeName: MeasurementTimestamp
              KeyType: RANGE
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.dynamoReadCapacity}
            WriteCapacityUnits: ${self:custom.dynamoWriteCapacity}
